---
- name: Install cgit dependencies
  become: yes
  apt: pkg={{ item }} state=present
  with_items:
    - python-setuptools
    - groff
    - libssl-dev
    - python3-pip
    - python3-setuptools
    - cgit

- name: Rename existing Apache cgit virtualhost
  become: yes
  command: >-
    mv /etc/apache2/sites-available/cgit /etc/apache2/sites-available/cgit.conf
    removes=/etc/apache2/sites-available/cgit

- name: Remove old sites-enabled/cgit symlink (new one will be created by a2ensite)
  become: yes
  file: path=/etc/apache2/sites-enabled/cgit state=absent

- name: Configure the Apache HTTP server for cgit
  become: yes
  template: src=etc_apache2_sites-available_cgit.j2
    dest=/etc/apache2/sites-available/cgit.conf
    group=root
    owner=root

- name: Enable Apache CGI module
  become: yes
  command: a2enmod cgi creates=/etc/apache2/mods-enabled/cgi.load
  notify: restart apache

- name: Enable Apache rewrite module
  become: yes
  command: a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load
  notify: restart apache

- name: Enable cgit site
  become: yes
  command: a2ensite cgit.conf creates=/etc/apache2/sites-enabled/cgit.conf
  notify: restart apache
